version: '3'

services:
  real-id-tracker:
    build: .
    container_name: real-id-tracker
    restart: unless-stopped
    volumes:
      # Mount the config file so it can be edited without rebuilding
      - ./src/config.js:/app/src/config.js
      # Mount the log file so it persists and can be viewed from the host
      - ./tracker.log:/app/tracker.log
    # Use the same timezone as the host
    environment:
      - TZ=America/New_York
