services:
  real-id-tracker:
    build: .
    container_name: real-id-tracker
    restart: unless-stopped
    # We'll use docker logs instead of volume mounting
    # Use the same timezone as the host
    environment:
      - TZ=America/New_York
      # Load environment variables from .env file
      - TRACKER_REGULAR_URL=${TRACKER_REGULAR_URL}
      - TRACKER_MOBILE_URL=${TRACKER_MOBILE_URL}
      - TRACKER_REGULAR_NOTIFICATION_URL=${TRACKER_REGULAR_NOTIFICATION_URL}
      - TRACKER_MOBILE_NOTIFICATION_URL=${TRACKER_MOBILE_NOTIFICATION_URL}
      - TRACKER_CHECK_INTERVAL=${TRACKER_CHECK_INTERVAL:-10}
      - TRACKER_EMAIL_SENDER=${TRACKER_EMAIL_SENDER}
      - TRACKER_EMAIL_RECIPIENT=${TRACKER_EMAIL_RECIPIENT}
      - TRACKER_EMAIL_PASSWORD=${TRACKER_EMAIL_PASSWORD}
      - TRACKER_EMAIL_SUBJECT=${TRACKER_EMAIL_SUBJECT:-"REAL ID Appointment Available"}
      - TRACKER_LOG_FILE=${TRACKER_LOG_FILE:-tracker.log}
      # Enhanced features
      - TRACKER_USE_API_SCRAPER=${TRACKER_USE_API_SCRAPER:-true}
      - TRACKER_DYNAMIC_INTERVALS=${TRACKER_DYNAMIC_INTERVALS:-true}
      - TRACKER_MIN_INTERVAL=${TRACKER_MIN_INTERVAL:-2}
      - TRACKER_MAX_INTERVAL=${TRACKER_MAX_INTERVAL:-30}
      - TRACKER_BUSINESS_HOURS_START=${TRACKER_BUSINESS_HOURS_START:-8}
      - TRACKER_BUSINESS_HOURS_END=${TRACKER_BUSINESS_HOURS_END:-18}
      - TRACKER_RANDOMIZE_INTERVAL=${TRACKER_RANDOMIZE_INTERVAL:-true}
      - TRACKER_JITTER_PERCENT=${TRACKER_JITTER_PERCENT:-20}
      - TRACKER_LOG_LEVEL=${TRACKER_LOG_LEVEL:-info}
      - TRACKER_REQUEST_TIMEOUT=${TRACKER_REQUEST_TIMEOUT:-30000}
      - TRACKER_MAX_RETRIES=${TRACKER_MAX_RETRIES:-3}
      - TRACKER_USER_AGENT=${TRACKER_USER_AGENT:-"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
    # Uncomment to use a .env file directly
    # env_file:
    #   - .env
