services:
  real-id-tracker:
    build: .
    container_name: real-id-tracker
    restart: unless-stopped
    # We'll use docker logs instead of volume mounting
    # Use the same timezone as the host
    environment:
      - TZ=America/New_York
      # Load environment variables from .env file
      - TRACKER_REGULAR_URL=${TRACKER_REGULAR_URL}
      - TRACKER_MOBILE_URL=${TRACKER_MOBILE_URL}
      - TRACKER_REGULAR_NOTIFICATION_URL=${TRACKER_REGULAR_NOTIFICATION_URL}
      - TRACKER_MOBILE_NOTIFICATION_URL=${TRACKER_MOBILE_NOTIFICATION_URL}
      - TRACKER_CHECK_INTERVAL=${TRACKER_CHECK_INTERVAL:-10}
      - TRACKER_EMAIL_SENDER=${TRACKER_EMAIL_SENDER}
      - TRACKER_EMAIL_RECIPIENT=${TRACKER_EMAIL_RECIPIENT}
      - TRACKER_EMAIL_PASSWORD=${TRACKER_EMAIL_PASSWORD}
      - TRACKER_EMAIL_SUBJECT=${TRACKER_EMAIL_SUBJECT}
      - TRACKER_LOG_FILE=${TRACKER_LOG_FILE:-tracker.log}
    # Uncomment to use a .env file directly
    # env_file:
    #   - .env
